import { createHash } from "node:crypto";
import { cpSync, existsSync, lstatSync, mkdirSync, opendirSync, renameSync, rmSync } from "node:fs";
import { isAbsolute, join, relative, resolve, dirname } from "node:path";
import { WOLFPACK_DIR } from "../cli/config.ts";
import { getInstallationId } from "../tailnet-machine-installation.ts";
import { writePrivateJsonFile } from "../server/persistence.ts";
import { compileStaticDocumentSchema, type ExtensionDocumentKey, type StaticSchemaValidator } from "./document-contract.ts";
import { readBoundedRegularFile } from "./bounded-file.ts";
import { parseExtensionPackageManifest, type ExtensionPackageManifest } from "./manifest.ts";
import { extractVerifiedNpmTarball, fetchExactNpmPackage } from "./package-security.ts";
import { assertPortablePackagePath } from "./portable-path.ts";
import { deployBundledPiSkills, removeBundledPiSkills, validateBundledPiSkills, type BundledPiSkill, type PiSkillDeploymentResult } from "./pi-skill-deployment.ts";
import type { ExtensionCatalogEnvelope, ExtensionCatalogInstallation } from "./runtime-contract.ts";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const DIGEST = /^[a-f0-9]{64}$/;
const MAX_FILE_BYTES = 2 * 1024 * 1024;
const MAX_FILES = 4_000;
export interface InstalledExtension { readonly installationId: string; readonly extensionId: string; readonly package: { readonly name: string; readonly version: string; readonly digest: string }; readonly snapshot: string; readonly enabled: boolean; readonly removed?: boolean; readonly previous?: { readonly version: string; readonly snapshot: string; readonly digest: string }; }
interface ExtensionRegistry { readonly version: 1; readonly installations: readonly InstalledExtension[]; }
export class ExtensionRuntimeError extends Error { constructor(readonly code: "INVALID_SOURCE" | "NOT_INSTALLED" | "DISABLED" | "BUSY" | "REGISTRY_CORRUPT" | "INCOMPATIBLE_SCHEMA", message: string) { super(message); this.name = "ExtensionRuntimeError"; } }
export interface InstallExtensionOptions { readonly source: string; readonly trustBrowserCode: boolean; readonly skillsRoot?: string; readonly registryUrl?: string; }
export interface ExtensionRuntimeOptions { readonly root?: string; readonly skillsRoot?: string; readonly installationId?: string; }
const hash = (bytes: Buffer | string) => createHash("sha256").update(bytes).digest("hex");
function readFile(path: string): Buffer {
  try { return readBoundedRegularFile(path, MAX_FILE_BYTES); }
  catch { throw new ExtensionRuntimeError("INVALID_SOURCE", "extension snapshot contains an invalid bounded file"); }
}
interface DeclaredDocument { readonly id: string; readonly schemaVersion: number; readonly schema: string; readonly bytes: Buffer; }
interface Declarations { readonly ui?: string; readonly docs: readonly DeclaredDocument[]; }

/** Owns only private snapshots under root; package JS is never imported. */
export class ExtensionRuntime {
  readonly root: string; readonly installationId: string; private readonly skillsRoot?: string;
  /** Validators are keyed by bytes read from a freshly verified snapshot, never registry claims alone. */
  private readonly validatorCache = new Map<string, StaticSchemaValidator>();
  constructor(options: ExtensionRuntimeOptions = {}) { this.root = options.root ?? join(WOLFPACK_DIR, "extensions"); this.skillsRoot = options.skillsRoot; this.installationId = options.installationId ?? getInstallationId(); if (!UUID.test(this.installationId)) throw new ExtensionRuntimeError("REGISTRY_CORRUPT", "host installation identity must be a canonical UUID"); }
  private registryPath() { return join(this.root, "registry.json"); } private snapshots() { return join(this.root, "snapshots"); }
  private ensureRoot() { mkdirSync(this.root, { recursive: true, mode: 0o700 }); const stat = lstatSync(this.root); if (!stat.isDirectory() || stat.isSymbolicLink()) throw new ExtensionRuntimeError("REGISTRY_CORRUPT", "extension root is not a private directory"); mkdirSync(this.snapshots(), { recursive: true, mode: 0o700 }); }
  private ownedSnapshot(path: string): boolean { const root = `${resolve(this.snapshots())}/`; return typeof path === "string" && resolve(path).startsWith(root) && resolve(path) !== resolve(this.snapshots()); }
  private registry(): ExtensionRegistry { this.ensureRoot(); if (!existsSync(this.registryPath())) return { version: 1, installations: [] }; try { const value: unknown = JSON.parse(readFile(this.registryPath()).toString("utf8")); if (!value || typeof value !== "object" || (value as any).version !== 1 || !Array.isArray((value as any).installations)) throw new Error(); const entries = (value as ExtensionRegistry).installations; const ids = new Set<string>(); const coherent = (path: string, digest: string, extensionId: string, name: string, version: string) => { if (!this.ownedSnapshot(path) || resolve(path) !== join(resolve(this.snapshots()), digest)) return false; const copied = this.inventory(path); if (copied.digest !== digest) return false; const manifest = this.manifest(path); return manifest.wolfpack.id === extensionId && manifest.name === name && manifest.version === version; }; for (const entry of entries) { if (!UUID.test(entry.installationId) || entry.installationId !== this.installationId || !/^[a-z][a-z0-9-]{0,63}$/.test(entry.extensionId) || ids.has(entry.extensionId) || !entry.package || !DIGEST.test(entry.package.digest) || !coherent(entry.snapshot, entry.package.digest, entry.extensionId, entry.package.name, entry.package.version) || (entry.previous && (!DIGEST.test(entry.previous.digest) || !coherent(entry.previous.snapshot, entry.previous.digest, entry.extensionId, entry.package.name, entry.previous.version)))) throw new Error(); ids.add(entry.extensionId); } return value as ExtensionRegistry; } catch { throw new ExtensionRuntimeError("REGISTRY_CORRUPT", "extension registry is not a coherent owned registry"); } }
  private save(value: ExtensionRegistry) { writePrivateJsonFile(this.registryPath(), value); }
  private withLock<T>(fn: () => T): T { this.ensureRoot(); const lock = join(this.root, ".registry-lock"); try { mkdirSync(lock, { mode: 0o700 }); } catch { throw new ExtensionRuntimeError("BUSY", "extension registry has an active transaction; no automatic recovery"); } try { return fn(); } finally { rmSync(lock, { recursive: true, force: true }); } }
  private inventory(root: string): { readonly files: readonly string[]; readonly digest: string } { const stat = lstatSync(root); if (!stat.isDirectory() || stat.isSymbolicLink()) throw new ExtensionRuntimeError("INVALID_SOURCE", "extension snapshot must be a regular directory"); const files: Array<{ path: string; digest: string }> = []; const walk = (dir: string) => { const entries = opendirSync(dir); try { for (let entry = entries.readSync(); entry; entry = entries.readSync()) { const full = join(dir, entry.name); const path = relative(root, full).replaceAll("\\", "/"); assertPortablePackagePath(path); const current = lstatSync(full); if (current.isSymbolicLink() || (!current.isDirectory() && !current.isFile())) throw new ExtensionRuntimeError("INVALID_SOURCE", "extension snapshot contains links or special files"); if (current.isDirectory()) walk(full); else { files.push({ path, digest: hash(readFile(full)) }); if (files.length > MAX_FILES) throw new ExtensionRuntimeError("INVALID_SOURCE", "extension has too many files"); } } } finally { entries.closeSync(); } }; walk(root); files.sort((left, right) => left.path.localeCompare(right.path)); if (!files.some((file) => file.path === "package.json")) throw new ExtensionRuntimeError("INVALID_SOURCE", "extension requires package.json"); return { files: files.map((file) => `${file.path}\0${file.digest}`), digest: hash(files.map((file) => `${file.path}\0${file.digest}`).join("\n")) }; }
  private sameInventory(left: { readonly files: readonly string[]; readonly digest: string }, right: { readonly files: readonly string[]; readonly digest: string }) { return left.digest === right.digest && left.files.length === right.files.length && left.files.every((file, index) => file === right.files[index]); }
  private copySnapshot(source: string): { snapshot: string; digest: string } { if (!isAbsolute(source)) throw new ExtensionRuntimeError("INVALID_SOURCE", "local extension source must be an absolute directory"); const root = resolve(source); const expected = this.inventory(root); const destination = join(this.snapshots(), expected.digest); const stage = join(this.snapshots(), `.stage-${process.pid}-${Date.now()}`); try { cpSync(root, stage, { recursive: true, dereference: false, errorOnExist: true }); const copied = this.inventory(stage); if (!this.sameInventory(expected, copied)) throw new ExtensionRuntimeError("INVALID_SOURCE", "copied extension snapshot differs from the validated source inventory"); if (!existsSync(destination)) renameSync(stage, destination); else { if (!this.sameInventory(expected, this.inventory(destination))) throw new ExtensionRuntimeError("REGISTRY_CORRUPT", "existing immutable extension snapshot differs from its digest inventory"); rmSync(stage, { recursive: true, force: true }); } return { snapshot: destination, digest: expected.digest }; } catch (error) { rmSync(stage, { recursive: true, force: true }); throw error; } }
  private async snapshot(source: string, registryUrl?: string) { if (!source.startsWith("npm:")) return this.copySnapshot(source); const acquisition = join(this.root, "acquisition"); mkdirSync(acquisition, { recursive: true, mode: 0o700 }); let extracted: string | undefined; let download: string | undefined; try { const pack = await fetchExactNpmPackage(source, acquisition, { registryUrl }); download = dirname(pack.tarball); extracted = await extractVerifiedNpmTarball(pack.tarball, this.snapshots(), { integrity: pack.integrity }); return this.copySnapshot(extracted); } finally { if (extracted) rmSync(dirname(extracted), { recursive: true, force: true }); if (download) rmSync(download, { recursive: true, force: true }); } }
  private manifest(snapshot: string): ExtensionPackageManifest { try { return parseExtensionPackageManifest(JSON.parse(readFile(join(snapshot, "package.json")).toString("utf8"))); } catch (error) { throw new ExtensionRuntimeError("INVALID_SOURCE", error instanceof Error ? error.message : "invalid extension manifest"); } }
  /** Read every declaration exactly once; catalog and assets need metadata, not AJV compilation. */
  private declarations(snapshot: string, manifest = this.manifest(snapshot)): Declarations {
    const ui = manifest.wolfpack.ui;
    if (ui) { if (!ui.endsWith(".js")) throw new ExtensionRuntimeError("INVALID_SOURCE", "declared UI must be a JavaScript asset"); if (readFile(join(snapshot, ui)).byteLength > 1024 * 1024) throw new ExtensionRuntimeError("INVALID_SOURCE", "declared UI exceeds the fixed 1 MiB browser-loader limit"); }
    return { ui, docs: manifest.wolfpack.documents.map(doc => ({ ...doc, bytes: readFile(join(snapshot, doc.schema)) })) };
  }
  private validator(bytes: Buffer): StaticSchemaValidator {
    const digest = hash(bytes), cached = this.validatorCache.get(digest);
    if (cached) return cached;
    const validator = compileStaticDocumentSchema(JSON.parse(bytes.toString("utf8")));
    this.validatorCache.set(digest, validator);
    if (this.validatorCache.size > 32) this.validatorCache.delete(this.validatorCache.keys().next().value!);
    return validator;
  }
  private catalogEntry(entry: InstalledExtension): ExtensionCatalogInstallation { const manifest = this.manifest(entry.snapshot); const declared = this.declarations(entry.snapshot, manifest); return { installationId: this.installationId, extensionId: entry.extensionId, package: entry.package, enabled: entry.enabled, ...(declared.ui ? { ui: { path: declared.ui, digest: hash(readFile(join(entry.snapshot, declared.ui))), mime: "text/javascript" as const, url: `/api/extensions/assets/${entry.extensionId}/${entry.package.digest}/${declared.ui}` } } : {}), documents: declared.docs.map((doc) => ({ id: doc.id, schemaVersion: doc.schemaVersion })) }; }
  catalog(safeMode = false): ExtensionCatalogEnvelope { const registry = this.registry(); return { safeMode, installations: registry.installations.filter((entry) => !entry.removed).map((entry) => this.catalogEntry(entry)) }; }
  private getFromRegistry(registry: ExtensionRegistry, extensionId: string) { const entry = registry.installations.find((item) => item.extensionId === extensionId && !item.removed); if (!entry) throw new ExtensionRuntimeError("NOT_INSTALLED", "extension is not installed"); return entry; }
  get(extensionId: string) { return this.getFromRegistry(this.registry(), extensionId); }
  declaration(extensionId: string, documentId: string) { const entry = this.getFromRegistry(this.registry(), extensionId); const doc = this.declarations(entry.snapshot).docs.find((item) => item.id === documentId); if (!doc) throw new ExtensionRuntimeError("NOT_INSTALLED", "document is not declared by installed extension"); return { entry, document: doc }; }
  schema(key: ExtensionDocumentKey): StaticSchemaValidator { const { entry, document } = this.declaration(key.extensionId, key.documentId); if (!entry.enabled) throw new ExtensionRuntimeError("DISABLED", "extension is disabled"); if (key.installationId !== this.installationId) throw new ExtensionRuntimeError("NOT_INSTALLED", "host installation does not own this extension"); return this.validator(document.bytes); }
  asset(extensionId: string, packageDigest: string, assetPath: string) { const entry = this.getFromRegistry(this.registry(), extensionId); if (!entry.enabled || entry.package.digest !== packageDigest) throw new ExtensionRuntimeError("NOT_INSTALLED", "extension asset is unavailable"); const ui = this.declarations(entry.snapshot).ui; if (!ui || ui !== assetPath) throw new ExtensionRuntimeError("NOT_INSTALLED", "extension asset is not allowlisted"); const bytes = readFile(join(entry.snapshot, ui)); return { bytes, digest: hash(bytes) }; }
  async install(options: InstallExtensionOptions): Promise<{ readonly installation: InstalledExtension; readonly skills: readonly PiSkillDeploymentResult[] }> { if (!options.trustBrowserCode) throw new ExtensionRuntimeError("INVALID_SOURCE", "explicit browser-code trust is required"); this.ensureRoot(); const snapshot = await this.snapshot(options.source, options.registryUrl); try { const manifest = this.manifest(snapshot.snapshot); const declared = this.declarations(snapshot.snapshot, manifest); for (const document of declared.docs) this.validator(document.bytes); const bundledSkills = this.bundledSkills(manifest, snapshot.snapshot); try { validateBundledPiSkills(manifest.wolfpack.id, bundledSkills); } catch (error) { throw new ExtensionRuntimeError("INVALID_SOURCE", error instanceof Error ? error.message : "declared skills are invalid"); } const committed = this.withLock(() => { const registry = this.registry(); const old = registry.installations.find((entry) => entry.extensionId === manifest.wolfpack.id); if (old && old.package.name !== manifest.name) throw new ExtensionRuntimeError("INVALID_SOURCE", "extension ID is already owned by a different package"); if (old && this.incompatible(old, declared.docs)) throw new ExtensionRuntimeError("INCOMPATIBLE_SCHEMA", "schema-changing updates require explicit migration support"); const installation: InstalledExtension = { installationId: this.installationId, extensionId: manifest.wolfpack.id, package: { name: manifest.name, version: manifest.version, digest: snapshot.digest }, snapshot: snapshot.snapshot, enabled: old?.enabled ?? true, removed: false, ...(old ? { previous: { version: old.package.version, snapshot: old.snapshot, digest: old.package.digest } } : {}) }; this.save({ version: 1, installations: [...registry.installations.filter((entry) => entry.extensionId !== manifest.wolfpack.id), installation] }); return installation; }); const skills = options.skillsRoot ?? this.skillsRoot ? deployBundledPiSkills({ skillsRoot: options.skillsRoot ?? this.skillsRoot!, extensionId: manifest.wolfpack.id, skills: bundledSkills }) : []; return { installation: committed, skills }; } catch (error) { if (this.ownedSnapshot(snapshot.snapshot) && !this.registry().installations.some((entry) => entry.snapshot === snapshot.snapshot)) rmSync(snapshot.snapshot, { recursive: true, force: true }); throw error; } }
  private incompatible(old: InstalledExtension, docs: readonly { id: string; schemaVersion: number; bytes: Buffer }[]) { const previous = this.declarations(old.snapshot).docs; return previous.length !== docs.length || previous.some((doc) => { const next = docs.find((value) => value.id === doc.id); return !next || next.schemaVersion !== doc.schemaVersion || !next.bytes.equals(doc.bytes); }); }
  private bundledSkills(manifest: ExtensionPackageManifest, snapshot: string): BundledPiSkill[] { return manifest.wolfpack.skills.map((path) => { const dir = join(snapshot, path); const files: Array<{ path: string; content: string }> = []; const walk = (at: string) => { const entries = opendirSync(at); try { for (let item = entries.readSync(); item; item = entries.readSync()) { const full = join(at, item.name); if (item.isDirectory()) walk(full); else if (item.isFile()) files.push({ path: relative(dir, full).replaceAll("\\", "/"), content: readFile(full).toString("utf8") }); else throw new ExtensionRuntimeError("INVALID_SOURCE", "skill contains unsupported entry"); } } finally { entries.closeSync(); } }; if (!lstatSync(dir).isDirectory()) throw new ExtensionRuntimeError("INVALID_SOURCE", "declared skill is missing"); walk(dir); return { name: path.split("/").at(-1)!, files }; }); }
  setEnabled(extensionId: string, enabled: boolean) { return this.withLock(() => { const registry = this.registry(); const old = this.getFromRegistry(registry, extensionId); const next = { ...old, enabled }; this.save({ version: 1, installations: registry.installations.map((entry) => entry.extensionId === extensionId ? next : entry) }); return next; }); }
  remove(extensionId: string, skillsRoot?: string) { return this.withLock(() => { const registry = this.registry(); const old = this.getFromRegistry(registry, extensionId); const manifest = this.manifest(old.snapshot); const results = skillsRoot ?? this.skillsRoot ? removeBundledPiSkills({ skillsRoot: skillsRoot ?? this.skillsRoot!, extensionId, names: manifest.wolfpack.skills.map((item) => item.split("/").at(-1)!) }) : []; this.save({ version: 1, installations: registry.installations.map((entry) => entry.extensionId === extensionId ? { ...entry, enabled: false, removed: true } : entry) }); return results; }); }
  purge(extensionId: string) { this.withLock(() => { const registry = this.registry(); const entry = registry.installations.find((item) => item.extensionId === extensionId); if (!entry) throw new ExtensionRuntimeError("NOT_INSTALLED", "extension has no retained installation"); this.removeOwnedDocuments(extensionId); this.save({ version: 1, installations: registry.installations.filter((item) => item.extensionId !== extensionId) }); rmSync(entry.snapshot, { recursive: true, force: true }); if (entry.previous) rmSync(entry.previous.snapshot, { recursive: true, force: true }); }); }
  private removeOwnedDocuments(extensionId: string) { const docs = join(this.root, "documents"); if (!existsSync(docs)) return; const files = opendirSync(docs); try { for (let file = files.readSync(); file; file = files.readSync()) { if (!file.isFile()) throw new ExtensionRuntimeError("REGISTRY_CORRUPT", "document directory contains an unexpected entry"); const path = join(docs, file.name); const value = JSON.parse(readFile(path).toString("utf8")); if (value?.key?.installationId === this.installationId && value.key.extensionId === extensionId) { rmSync(path); if (existsSync(path)) throw new ExtensionRuntimeError("REGISTRY_CORRUPT", "document cleanup requires recovery"); } } } finally { files.closeSync(); } }
  rollback(extensionId: string) { return this.withLock(() => { const registry = this.registry(); const old = this.getFromRegistry(registry, extensionId); if (!old.previous) throw new ExtensionRuntimeError("INVALID_SOURCE", "extension has no retained previous version"); const next = { ...old, package: { ...old.package, version: old.previous.version, digest: old.previous.digest }, snapshot: old.previous.snapshot, previous: { version: old.package.version, snapshot: old.snapshot, digest: old.package.digest } }; this.save({ version: 1, installations: registry.installations.map((entry) => entry.extensionId === extensionId ? next : entry) }); return next; }); }
}
let runtime: ExtensionRuntime | undefined; export function getExtensionRuntime() { return runtime ??= new ExtensionRuntime(); } export function __setExtensionRuntimeForTests(value: ExtensionRuntime | undefined) { if (!process.env.WOLFPACK_TEST) throw new Error("test-only extension runtime override"); runtime = value; }
