#!/usr/bin/env bun
/**
 * Bundles public/app.ts into public/app.bundle.js for browser consumption.
 * Uses Bun.build() with browser target and IIFE output so app internals do not
 * become mutable window properties.
 *
 * Output: public/app.bundle.js
 *
 * Usage in HTML:
 *   <script src="/app.bundle.js"></script>
 */
import { join } from "node:path";
import { writeFileSync, existsSync } from "node:fs";

const ROOT = join(import.meta.dirname, "..");
const ENTRY = join(ROOT, "public", "app.ts");
const OUT_PATH = join(ROOT, "public", "app.bundle.js");

if (!existsSync(ENTRY)) {
  console.error(`bundle-app: ${ENTRY} not found — skipping`);
  process.exit(0);
}

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: "browser",
  format: "iife",
  minify: { whitespace: true, syntax: true, identifiers: true },
});

if (!result.success) {
  console.error("bundle-app failed:", result.logs);
  process.exit(1);
}

const code = (await result.outputs[0].text()).trim();

const bundle = `// AUTO-GENERATED by scripts/bundle-app.ts — do not edit
${code}
`;

writeFileSync(OUT_PATH, bundle);
const sizeKB = (Buffer.byteLength(bundle) / 1024).toFixed(1);
console.log(`bundled app → ${OUT_PATH} (${sizeKB} KB)`);
