#!/usr/bin/env bun
/**
 * Bundles ghostty-web into public/, then generates public-assets.ts — a module
 * that embeds all files from public/ as a
 * Map<string, { content: string | Uint8Array; mime: string }>.
 *
 * Run: bun run scripts/gen-assets.ts
 * Output: src/public-assets.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";
import { execSync } from "node:child_process";
import { createHash } from "node:crypto";

const ROOT = join(import.meta.dirname, "..");
const PUBLIC_DIR = join(ROOT, "public");
const OUT_FILE = join(ROOT, "src", "public-assets.ts");
const ASSET_VERSION_TOKEN = "__WOLFPACK_ASSET_VERSION__";

const MIME_MAP: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".json": "application/json",
  ".js": "application/javascript",
  ".css": "text/css",
  ".txt": "text/plain; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".webp": "image/webp",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".ttf": "font/ttf",
};

const TEXT_EXTS = new Set([".html", ".json", ".js", ".css", ".svg", ".txt", ".xml"]);

function isText(ext: string): boolean {
  return TEXT_EXTS.has(ext);
}

// Bundle ghostty-web into public/ (replaces old xterm copy step)
console.log("bundling ghostty-web...");
execSync("bun run scripts/bundle-ghostty.ts", {
  cwd: join(import.meta.dirname, ".."),
  stdio: "inherit",
});

// Bundle client-side pure logic modules into public/wolfpack-lib.js
console.log("bundling wolfpack-lib...");
execSync("bun run scripts/bundle-client-lib.ts", {
  cwd: join(import.meta.dirname, ".."),
  stdio: "inherit",
});

// Bundle public/app.ts into public/app.bundle.js
console.log("bundling app...");
execSync("bun run scripts/bundle-app.ts", {
  cwd: join(import.meta.dirname, ".."),
  stdio: "inherit",
});

const files = readdirSync(PUBLIC_DIR).sort();
const versionHash = createHash("sha256");
const assetVersions = new Map<string, string>();
for (const file of files) {
  if (extname(file).toLowerCase() === ".ts") continue;
  const bytes = readFileSync(join(PUBLIC_DIR, file));
  versionHash.update(file);
  versionHash.update("\0");
  versionHash.update(bytes);
  assetVersions.set(file, createHash("sha256").update(bytes).digest("hex").slice(0, 16));
}
const assetVersion = versionHash.digest("hex").slice(0, 16);
const entries: string[] = [];

function versionIndexAssetUrls(source: string): string {
  return source.replace(
    /(src|href|content)="\/([^"?]+)\?v=__WOLFPACK_ASSET_VERSION__"/g,
    (match, attribute: string, file: string) => {
      const version = assetVersions.get(file);
      return version ? `${attribute}="/${file}?v=${version}"` : match;
    },
  );
}

function versionServiceWorkerAssetUrls(source: string): string {
  return source.replace(
    /"\/([^"?]+)\?v=__WOLFPACK_ASSET_VERSION__"/g,
    (match, file: string) => {
      const version = assetVersions.get(file);
      return version ? `"/${file}?v=${version}"` : match;
    },
  );
}

for (const file of files) {
  const ext = extname(file).toLowerCase();
  // Skip .ts source files — only serve compiled bundles
  if (ext === ".ts") continue;
  const mime = MIME_MAP[ext] ?? "application/octet-stream";
  const filePath = join(PUBLIC_DIR, file);

  if (isText(ext)) {
    const source = readFileSync(filePath, "utf-8");
    let content = source;
    if (file === "index.html") {
      content = versionIndexAssetUrls(source).replaceAll(ASSET_VERSION_TOKEN, assetVersion);
    } else if (file === "sw.js") {
      content = versionServiceWorkerAssetUrls(source);
    }
    // Use JSON.stringify to safely embed the string
    entries.push(
      `  [${JSON.stringify(file)}, { content: ${JSON.stringify(content)}, mime: ${JSON.stringify(mime)} }]`,
    );
  } else {
    // Binary: embed as base64, decode at import time
    const buf = readFileSync(filePath);
    const b64 = buf.toString("base64");
    entries.push(
      `  [${JSON.stringify(file)}, { content: _b64(${JSON.stringify(b64)}), mime: ${JSON.stringify(mime)} }]`,
    );
  }
}

const output = `// AUTO-GENERATED by scripts/gen-assets.ts — do not edit
// Embeds all files from public/ for bun compile single-binary distribution.

function _b64(s: string): Uint8Array {
  return Buffer.from(s, "base64");
}

export const ASSET_VERSION = ${JSON.stringify(assetVersion)};
export const ASSET_VERSIONS: Readonly<Record<string, string>> = Object.freeze(${JSON.stringify(Object.fromEntries(assetVersions))});

export const assets = new Map<string, { content: string | Uint8Array; mime: string }>([
${entries.join(",\n")},
]);
`;

writeFileSync(OUT_FILE, output);
console.log(`generated ${OUT_FILE} (${files.length} files embedded)`);
