import { AGENT_KIND, OPENABLE_HARNESSES } from "./agent-kind.js";
import type { OpenableHarness } from "./agent-kind.js";

export const SESSION_CREATE_HARNESSES = [
  ...OPENABLE_HARNESSES,
  AGENT_KIND.SHELL,
] as const;

export type SessionCreateHarness = OpenableHarness | typeof AGENT_KIND.SHELL;

const SESSION_CREATE_HARNESS_SET: ReadonlySet<string> = new Set(SESSION_CREATE_HARNESSES);

export function isSessionCreateHarness(value: string): value is SessionCreateHarness {
  return SESSION_CREATE_HARNESS_SET.has(value);
}

export const SESSION_CREATE_ERROR = {
  INVALID_REQUEST: "INVALID_REQUEST",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PARENT_SESSION_NOT_FOUND: "PARENT_SESSION_NOT_FOUND",
  PARENT_SESSION_CHANGED: "PARENT_SESSION_CHANGED",
  PARENT_IDENTITY_UNAVAILABLE: "PARENT_IDENTITY_UNAVAILABLE",
  UNSUPPORTED_HARNESS: "UNSUPPORTED_HARNESS",
  NAME_COLLISION: "NAME_COLLISION",
  BACKEND_UNAVAILABLE: "BACKEND_UNAVAILABLE",
} as const;

export type SessionCreateErrorCode = typeof SESSION_CREATE_ERROR[keyof typeof SESSION_CREATE_ERROR];

export const SESSION_CREATE_HTTP_STATUS = {
  [SESSION_CREATE_ERROR.INVALID_REQUEST]: 400,
  [SESSION_CREATE_ERROR.PROJECT_NOT_FOUND]: 404,
  [SESSION_CREATE_ERROR.PARENT_SESSION_NOT_FOUND]: 404,
  [SESSION_CREATE_ERROR.PARENT_SESSION_CHANGED]: 409,
  [SESSION_CREATE_ERROR.PARENT_IDENTITY_UNAVAILABLE]: 503,
  [SESSION_CREATE_ERROR.UNSUPPORTED_HARNESS]: 400,
  [SESSION_CREATE_ERROR.NAME_COLLISION]: 409,
  [SESSION_CREATE_ERROR.BACKEND_UNAVAILABLE]: 503,
} as const satisfies Readonly<Record<SessionCreateErrorCode, number>>;

const SESSION_CREATE_ERROR_SET: ReadonlySet<string> = new Set(Object.values(SESSION_CREATE_ERROR));

export function isSessionCreateErrorCode(value: string): value is SessionCreateErrorCode {
  return SESSION_CREATE_ERROR_SET.has(value);
}
