export {
  OPENABLE_HARNESSES,
  isOpenableHarness,
} from "./agent-kind.js";
export type { OpenableHarness } from "./agent-kind.js";

export const SESSION_OPEN_MAX_MODEL_LENGTH = 512;
export const SESSION_TASK_WORKER_DEFAULT_READINESS_TIMEOUT_MS = 30_000;
export const SESSION_TASK_WORKER_MAX_READINESS_TIMEOUT_MS = 60_000;
/** Bounds post-create exact-id cleanup; CLI response grace includes this budget. */
export const SESSION_TASK_WORKER_CLEANUP_TIMEOUT_MS = 3_000;
export const SESSION_TASK_WORKER_RESPONSE_GRACE_MS = 5_000;

export const SESSION_OPEN_ERROR = {
  INVALID_REQUEST: "INVALID_REQUEST",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PARENT_SESSION_NOT_FOUND: "PARENT_SESSION_NOT_FOUND",
  PARENT_SESSION_CHANGED: "PARENT_SESSION_CHANGED",
  PARENT_IDENTITY_UNAVAILABLE: "PARENT_IDENTITY_UNAVAILABLE",
  UNSUPPORTED_HARNESS: "UNSUPPORTED_HARNESS",
  NAME_COLLISION: "NAME_COLLISION",
  BACKEND_UNAVAILABLE: "BACKEND_UNAVAILABLE",
  TASK_WORKER_PREFLIGHT_FAILED: "TASK_WORKER_PREFLIGHT_FAILED",
  TASK_WORKER_NOT_READY: "TASK_WORKER_NOT_READY",
} as const;

export type SessionOpenErrorCode = typeof SESSION_OPEN_ERROR[keyof typeof SESSION_OPEN_ERROR];

export const SESSION_OPEN_HTTP_STATUS = {
  [SESSION_OPEN_ERROR.INVALID_REQUEST]: 400,
  [SESSION_OPEN_ERROR.PROJECT_NOT_FOUND]: 404,
  [SESSION_OPEN_ERROR.PARENT_SESSION_NOT_FOUND]: 404,
  [SESSION_OPEN_ERROR.PARENT_SESSION_CHANGED]: 409,
  [SESSION_OPEN_ERROR.PARENT_IDENTITY_UNAVAILABLE]: 503,
  [SESSION_OPEN_ERROR.UNSUPPORTED_HARNESS]: 400,
  [SESSION_OPEN_ERROR.NAME_COLLISION]: 409,
  [SESSION_OPEN_ERROR.BACKEND_UNAVAILABLE]: 503,
  [SESSION_OPEN_ERROR.TASK_WORKER_PREFLIGHT_FAILED]: 503,
  [SESSION_OPEN_ERROR.TASK_WORKER_NOT_READY]: 503,
} as const satisfies Readonly<Record<SessionOpenErrorCode, number>>;

const SESSION_OPEN_ERROR_SET: ReadonlySet<string> = new Set(Object.values(SESSION_OPEN_ERROR));

export function isSessionOpenErrorCode(value: string): value is SessionOpenErrorCode {
  return SESSION_OPEN_ERROR_SET.has(value);
}
